language: android

jdk:
  - oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - android-25
    - extra
    - addon
    - build-tools-25.0.0
    - sys-img-armeabi-v7a-android-22

script:
  - ./gradlew